// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Booth struct {
	ID        int32
	Name      string
	Organizer string
	Detail    string
	Location  sql.NullString
	ImageUrl  sql.NullString
	X         float64
	Y         float64
	Z         float64
	Latitude  sql.NullFloat64
	Longitude sql.NullFloat64
}

type Performer struct {
	ID           int32
	BlockID      int32
	Name         string
	Detail       string
	ThumbnailUrl string
	PerformOrder int32
}

type StageBlock struct {
	ID           int32
	SectionID    int32
	StartTime    time.Time
	EndTime      time.Time
	CurrentOrder int32
}

type StageSection struct {
	ID        int32
	Name      string
	Location  string
	SortOrder int32
}

type User struct {
	ID              string
	LoginID         string
	Name            string
	AssignedBoothID sql.NullInt32
	Password        string
	Role            string
}
