// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Booth struct {
	ID               int32
	Name             string
	Organizer        string
	Detail           string
	CongestionStatus int8
	X                float64
	Y                float64
	Z                float64
}

type Live struct {
	ID            int32
	Name          string
	Detail        sql.NullString
	Thumbnailurl  sql.NullString
	StartTime     time.Time
	EndTime       time.Time
	SessionNumber sql.NullInt16
	Status        int8
}

type User struct {
	ID              string
	Name            string
	AssignedBoothID sql.NullInt32
	Password        string
	Role            string
}
