// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createBooth = `-- name: CreateBooth :execresult
INSERT INTO booths (
name, organizer, detail, congestion_status, x, y, z
) VALUES (
?, ?, ?, ?, ?, ?, ?
)
`

type CreateBoothParams struct {
	Name             string
	Organizer        string
	Detail           string
	CongestionStatus int8
	X                float64
	Y                float64
	Z                float64
}

func (q *Queries) CreateBooth(ctx context.Context, arg CreateBoothParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBooth,
		arg.Name,
		arg.Organizer,
		arg.Detail,
		arg.CongestionStatus,
		arg.X,
		arg.Y,
		arg.Z,
	)
}

const createLive = `-- name: CreateLive :exec
INSERT INTO lives (
name, detail, thumbnailURL, start_time, end_time, session_number, status
) VALUES (
?, ?, ?, ?, ?, ?, ?
)
`

type CreateLiveParams struct {
	Name          string
	Detail        sql.NullString
	Thumbnailurl  sql.NullString
	StartTime     time.Time
	EndTime       time.Time
	SessionNumber sql.NullInt16
	Status        int8
}

func (q *Queries) CreateLive(ctx context.Context, arg CreateLiveParams) error {
	_, err := q.db.ExecContext(ctx, createLive,
		arg.Name,
		arg.Detail,
		arg.Thumbnailurl,
		arg.StartTime,
		arg.EndTime,
		arg.SessionNumber,
		arg.Status,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
id, name, assigned_booth_id, password, role
) VALUES (
?, ?, ?, ?, ?
)
`

type CreateUserParams struct {
	ID              string
	Name            string
	AssignedBoothID sql.NullInt32
	Password        string
	Role            string
}

// usersテーブルはIDがUUID(VARCHAR)の指定だったため、挿入時にIDも受け取ります
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.AssignedBoothID,
		arg.Password,
		arg.Role,
	)
	return err
}

const deleteBooth = `-- name: DeleteBooth :exec
DELETE FROM booths WHERE id = ?
`

func (q *Queries) DeleteBooth(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteBooth, id)
	return err
}

const deleteLive = `-- name: DeleteLive :exec
DELETE FROM lives WHERE id = ?
`

func (q *Queries) DeleteLive(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteLive, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getAllBooths = `-- name: GetAllBooths :many
SELECT id, name, organizer, detail, congestion_status, x, y, z FROM booths
`

func (q *Queries) GetAllBooths(ctx context.Context) ([]Booth, error) {
	rows, err := q.db.QueryContext(ctx, getAllBooths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booth
	for rows.Next() {
		var i Booth
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Organizer,
			&i.Detail,
			&i.CongestionStatus,
			&i.X,
			&i.Y,
			&i.Z,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllLives = `-- name: GetAllLives :many
SELECT id, name, detail, thumbnailurl, start_time, end_time, session_number, status FROM lives
`

func (q *Queries) GetAllLives(ctx context.Context) ([]Live, error) {
	rows, err := q.db.QueryContext(ctx, getAllLives)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Live
	for rows.Next() {
		var i Live
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Detail,
			&i.Thumbnailurl,
			&i.StartTime,
			&i.EndTime,
			&i.SessionNumber,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, name, assigned_booth_id, password, role FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AssignedBoothID,
			&i.Password,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBoothByID = `-- name: GetBoothByID :one

SELECT id, name, organizer, detail, congestion_status, x, y, z FROM booths WHERE id = ?
`

// ==========================================
// Booths (ブース関連)
// ==========================================
func (q *Queries) GetBoothByID(ctx context.Context, id int32) (Booth, error) {
	row := q.db.QueryRowContext(ctx, getBoothByID, id)
	var i Booth
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Organizer,
		&i.Detail,
		&i.CongestionStatus,
		&i.X,
		&i.Y,
		&i.Z,
	)
	return i, err
}

const getCurrentLives = `-- name: GetCurrentLives :many
SELECT id, name, detail, thumbnailurl, start_time, end_time, session_number, status FROM lives WHERE status = 1
`

// statusの値は仮ですが、例えば1を「進行中」とした場合
func (q *Queries) GetCurrentLives(ctx context.Context) ([]Live, error) {
	rows, err := q.db.QueryContext(ctx, getCurrentLives)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Live
	for rows.Next() {
		var i Live
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Detail,
			&i.Thumbnailurl,
			&i.StartTime,
			&i.EndTime,
			&i.SessionNumber,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLiveByID = `-- name: GetLiveByID :one


SELECT id, name, detail, thumbnailurl, start_time, end_time, session_number, status FROM lives WHERE id = ?
`

// db/query.sql
// ==========================================
// Lives (ライブイベント関連)
// ==========================================
func (q *Queries) GetLiveByID(ctx context.Context, id int32) (Live, error) {
	row := q.db.QueryRowContext(ctx, getLiveByID, id)
	var i Live
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Detail,
		&i.Thumbnailurl,
		&i.StartTime,
		&i.EndTime,
		&i.SessionNumber,
		&i.Status,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, name, assigned_booth_id, password, role FROM users WHERE id = ?
`

// ==========================================
// Users (ユーザー関連)
// ==========================================
func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AssignedBoothID,
		&i.Password,
		&i.Role,
	)
	return i, err
}

const updateBooth = `-- name: UpdateBooth :exec
UPDATE booths
SET name = ?, organizer = ?, detail = ?, congestion_status = ?, x = ?, y = ?, z = ?
WHERE id = ?
`

type UpdateBoothParams struct {
	Name             string
	Organizer        string
	Detail           string
	CongestionStatus int8
	X                float64
	Y                float64
	Z                float64
	ID               int32
}

func (q *Queries) UpdateBooth(ctx context.Context, arg UpdateBoothParams) error {
	_, err := q.db.ExecContext(ctx, updateBooth,
		arg.Name,
		arg.Organizer,
		arg.Detail,
		arg.CongestionStatus,
		arg.X,
		arg.Y,
		arg.Z,
		arg.ID,
	)
	return err
}

const updateLive = `-- name: UpdateLive :exec
UPDATE lives
SET name = ?, detail = ?, thumbnailURL = ?, start_time = ?, end_time = ?, session_number = ?, status = ?
WHERE id = ?
`

type UpdateLiveParams struct {
	Name          string
	Detail        sql.NullString
	Thumbnailurl  sql.NullString
	StartTime     time.Time
	EndTime       time.Time
	SessionNumber sql.NullInt16
	Status        int8
	ID            int32
}

func (q *Queries) UpdateLive(ctx context.Context, arg UpdateLiveParams) error {
	_, err := q.db.ExecContext(ctx, updateLive,
		arg.Name,
		arg.Detail,
		arg.Thumbnailurl,
		arg.StartTime,
		arg.EndTime,
		arg.SessionNumber,
		arg.Status,
		arg.ID,
	)
	return err
}
